### ISSUE TITLE
Adjust application typeform

### ISSUE THREAD

**Issue by usama9500** [Trusted-Seed/coordination#10]
## 📋   Anything to add?
https://trusted-seed-dashboard.netlify.app/apply-stage-two

- [ ] - Remove CS logo
- [ ] - Remove first screen or change text
- [ ] - Adjust form colors to match website theme colors. Use #12BAD6 is possible
- [ ] - Can we get rid of "Powered by typeform"?

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@
