### ISSUE TITLE
Trusted Seed Applicants Review

### ISSUE THREAD

**Issue by usama9500** [Trusted-Seed/coordination#103]
## 🎉   Subtasks

- [ ]  Assign Trust Scores
- [ ]  Prepare data to be uploaded to the CRM
- [ ]  Take care of any duplicates #551
- [ ]  Upload data to CRM and prepare emails by type of contributor (time and funds/both)
- [ ]  Update Registry https://blockscout.com/poa/xdai/address/0x73e7427428f6C77C180d17F48909780c839954a7/write-contract 
- [ ]  Send emails
- [ ]  Send custom 1-1 emails / messages when necessary

## 🤼‍♂️   Reviewer

@GriffGreen
