### ISSUE TITLE
Re-do our user journey (Urgent) Make it clear and info friendly!

### ISSUE THREAD

**Issue by usama9500** [Trusted-Seed/coordination#112]
From iteration0 created by [mafer-cordovas](https://github.com/mafer-cordovas): commons-stack/iteration0#1201  

## 📋   Anything to add?
Make the user journey as clear as possible. Currently, the activation part is not clear until way far in the process, and this might be influencing the successful applicants to not activate.
## 🎉   Subtasks

- [x] Add dues payment info to the Typeform
- [ ] Review all documentation related to the user journey
- [ ] Create an infographic to explain the whole process

## 🤼‍♂️   Reviewer

@tamarandom 

## 🔗   Work doc - inspirational links
- App form https://the-commons-stack.typeform.com/to/nG7xc1
- Process description https://medium.com/commonsstack/join-the-commons-stacks-trusted-seed-swiss-association-ed51a356cb6c

**Comment by usama9500** [comment]
Open sessions in discord's Treehouse with T!b! on Thursdays. 3 sessions so far.

**Comment by usama9500** [comment]
Changes to the Typeform 1st page
 ![image.png](https://images.zenhubusercontent.com/61140368d41f1f02056e127f/2a9351b6-f5e9-4b1d-8400-1f153a6b294d)

**Comment by usama9500** [comment]
Definitely Trusted Seed.

**Comment by usama9500** [comment]
@tamarandom is this Trusted Seed related issue or Commons Stack

**Comment by usama9500** [comment]
Assigning it to myself until Maria joins the Trusted Seed Board.
