### ISSUE TITLE
Checklist before launching the TS Dashboard and swag shop

### ISSUE THREAD

**Issue by kristoferlund** [Trusted-Seed/coordination#129]
## 📋   Anything to add?

There are a bunch of small issues that need to be closed before we can call the TS Dashboard launched.

### Payment
- [x] Deploy Collector contract to Gnosis @paxthemax
- [ ] Update the "bridge server" to monitor payments to the collector contract  @aminlatifi
- [ ] Bridge server should transfer 70 TSLOVE to everyone that pays membership dues @aminlatifi

### Giveth
- [x] Make sure the TS Giveth page clearly describes to the prospective TS member how much to pay, what can be expected afterwards, etc
- [ ] Configure Giveth to send funds to Collector contract

### TS Dashboard
- [x] Layout the About page @rodricastillo9013
- [ ] Update the application form to better align with new loook @YineisyM 
- [x] Find any remaining dummy texts and replace with real ones @kristoferlund 
- [ ] Upload list of old members and activation dates

### TS Swag shop @rbsal97
- [x] Make product designs @rodricastillo9013
- [x] Add products to shop @mafer-cordovas 
- [x] Create 2 x banners @rodricastillo9013
- [x] Add banners to shop @kkatusic

## 🤼‍♂️   Reviewer

Please add anything that is missing @GriffGreen @tamarandom @mafer-cordovas @MaxSemenchuk @YineisyM @iviangita

## 🔗   Work doc - inspirational links

-

**Comment by tamarandom** [comment]
Love it!
