### ISSUE TITLE
Review/Improve Notion for CS

### ISSUE THREAD

**Issue by usama9500** [Trusted-Seed/coordination#45]
From iteration0 created by [mafer-cordovas](https://github.com/mafer-cordovas): commons-stack/iteration0#1031  

## 🎉   Subtasks

- [ ] Check current pages
- [ ] Feedback from teams 
- [ ] Improvements around circles 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Should be assigned to Maria. Will assign to myself until she's in this Org. ;)
