### ISSUE TITLE
TSLove Swag follow-up

### ISSUE THREAD

**Issue by usama9500** [Trusted-Seed/coordination#47]
From iteration0 created by [mafer-cordovas](https://github.com/mafer-cordovas): commons-stack/iteration0#968  

## 📋   Anything to add?
The purpose is to have an overview of members who haven't claim their Swag items, item trends, and reach out reminders.
## 🎉   Subtasks

- [ ] Update CSLove airdrop data
- [ ] Update claimed items 
- [ ] Keep reminder fields updated with the latest reach out to members

## 🤼‍♂️   Reviewer

@knobsdao

**Comment by usama9500** [comment]
Assigning it to myself until Maria joins the board!

**Comment by mafer-labs** [comment]
Changing title to TSLOVE token and we will use this issue to plan new airdrop for current active members.
