### ISSUE TITLE
TS Scholarship Spreadsheet

### ISSUE THREAD

**Issue by usama9500** [Trusted-Seed/coordination#48]
From iteration0 created by [mafer-cordovas](https://github.com/mafer-cordovas): commons-stack/iteration0#967  

## 📋   Anything to add?
The goal for this spreadsheet is to get the total scholarships awarded by month, trace activity, and track membership activations. This spreadsheet will be updated by the Junior Gardeners 👩🏼‍🌾🌱
## 🎉   Subtasks

- [ ] Update Data from Giveth 
- [ ] Report monthly results 
- [ ] Track any issues that might come up with Scholarship traces

## 🤼‍♂️   Reviewer

@knobsdao

**Comment by usama9500** [comment]
Assigning it to myself until Maria joins the board.

**Comment by mafer-labs** [comment]
Since April 9, we have received 15 scholarship applications. 11 for renewals, 3 first time.
