### ISSUE TITLE
Host Monthly Contributors Sync Calls

### ISSUE THREAD

**Issue by usama9500** [Trusted-Seed/coordination#54]
From iteration0 created by [knobsdao](https://github.com/knobsdao): commons-stack/iteration0#715  

## 📋   Anything to add?
Scheduled for the last Thursday of each month at noon EST over Discord voice channel.

## 🎉   Subtasks

- [x] Make sure a member of the team can be present to host in case @mafer-cordovas or @YineisyM can't.
- [ ] Sync with the core team on where contributions of time are needed.
- [ ] Review issues marked "For Contributors"; and make new ones if needed.
- [ ] If a question, idea, etc. can't be answered there, make a note to channel it to the right space and/or follow-up.
- [ ] Continue to fine-tune the process.

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
- [Calendar link](https://calendar.google.com/event?action=TEMPLATE&tmeid=N2ZyOXYycHYzMDhmOGI5b2QxdmdiMmc1bDlfMjAyMTAzMThUMTYwMDAwWiBjX3ZqZGNrZmo0YmhhcnVvdmhkNHJtbzNkdHY0QGc&tmsrc=c_vjdckfj4bharuovhd4rmo3dtv4%40group.calendar.google.com&scp=ALL) just for this call.
- [Calendar link](https://calendar.google.com/calendar/u/0/embed?src=c_vjdckfj4bharuovhd4rmo3dtv4@group.calendar.google.com&ctz=Eastern/Time/New/York) for all calls.

**Comment by usama9500** [comment]
I'm taking the "for contributor" label out of this one so only action items for contributors have the label :)

**Comment by YineisyM** [comment]
Closing this issue for now. This call was canceled until we better define how people can contribute so we can guide them properly.
