### ISSUE TITLE
Ensure TS Data Integrity 

### ISSUE THREAD

**Issue by usama9500** [Trusted-Seed/coordination#56]
From iteration0 created by [tamarandom](https://github.com/tamarandom): commons-stack/iteration0#551  

## 📋   Anything to add?

This issue is a reminder for ongoing data integrity work across our data-sheets and the CRM during the sprint.

## 🎉   Subtasks

- [x] Create a list of TS Applicants that also hold TEC IH (done up till January 2021)
- [x] Build Group of TS Properties.
- [x] Build Group of MailChimp-related Properties
- [x] Take care of dupe applications
- [x] Merge duplicates in the CRM. [Ongoing]
- [ ] Other to come...

## 🤼‍♂️   Reviewer

@

**Comment by usama9500** [comment]
All identified dupes sorted, merged and/or marked for refinement.

**Comment by usama9500** [comment]
46 TS dupes identified and currently being sorted.

**Comment by tamarandom** [comment]
Assigning to myself until Maria accepts the Github invite! (Should be this week since she will be back home).
